root_dir: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset : artifacts/data_ingestion/imdb_dataset

data_transformation:
  root_dir: artifacts/data_transformation
  dataset: artifacts/data_ingestion/imdb_dataset
  tokenizer_name: "distilbert/distilbert-base-uncased"
  local_tokenizer: artifacts/data_transformation/tokenizer
  transformed_data: artifacts/data_transformation/transformed_data

model_trainer:
  root_dir: artifacts/model_trainer
  model_name: "distilbert/distilbert-base-uncased"
  tokenizer: artifacts/data_transformation/tokenizer
  transformed_data: artifacts/data_transformation/transformed_data
  local_model: artifacts/model_trainer/model